In [26]:
import cv2
import time
import numpy as np

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def draw_rect(frame, regressor, classificator, stride, anchor_count, column, row, anchor, offset):
    index = (int(row * 128 / stride) + column) * anchor_count + anchor + offset

    score = sigmoid(regressor[index][0])
    if score < 0.5: return

    x, y, w, h = classificator[index][:4]

    x += (column + 0.5) * stride - w / 2
    y += (row    + 0.5) * stride - h / 2
    x = int(x)
    y = int(y)
    w = int(w)
    h = int(h)
    frame = cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 1)

net = cv2.dnn.readNet('palm_detection.onnx')
outNames = net.getUnconnectedOutLayersNames()

print(outNames)
cap = cv2.VideoCapture(0)
while True:
    time_start = time.time()
    ret, frame = cap.read()

    frame = cv2.resize(frame, dsize=(128, 128))
    cv2.imwrite("frame.jpg", frame)
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    print(frame[100])
    #tensor = (frame / 127.5 - 1.0).reshape((128, 128, 3)).transpose(2, 0, 1)
    tensor = (frame / 127.5 - 1.0)
    #print(tensor[100])
    blob = cv2.dnn.blobFromImage(tensor.astype(np.float32), swapRB=False, crop=False)

    net.setInput(blob)
    preds = net.forward(outNames)
    regressor = preds[0]
    classifier = preds[1]

    for y in range(16):
        for x in range(16):
            for a in range(2):
                draw_rect(frame, regressor[0], classifier[0], 8, 2, x, y, a, 0)

    for y in range(8):
        for x in range(8):
            for a in range(6):
                draw_rect(frame, regressor[0], classifier[0], 16, 6, x, y, a, 512)
    
    frame = cv2.resize(frame, dsize=(640, 480))

    if cv2.waitKey(1) == ord('q'):
        break
    frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
    time_cur = time.time()
    cv2.putText(frame, f"time spend: {time_cur - time_start}", (0, 50), cv2.FONT_HERSHEY_SIMPLEX, 2, (125, 125, 125), 2)
    cv2.imshow('Camera Streaming', frame)

cap.release()
cv2.destroyAllWindows()


('classificators', 'regressors')
[[205 217 216]
 [203 216 216]
 [204 218 219]
 [202 216 217]
 [200 214 215]
 [201 215 216]
 [201 215 216]
 [202 216 217]
 [202 216 217]
 [202 216 217]
 [205 218 220]
 [205 218 220]
 [209 219 221]
 [209 220 222]
 [211 222 224]
 [209 223 224]
 [209 223 224]
 [149 162 171]
 [ 94 107 115]
 [ 87 100 108]
 [ 82  95 104]
 [ 79  89 101]
 [ 88  93 106]
 [ 62  72  87]
 [ 58  68  86]
 [ 63  72  90]
 [ 70  80  96]
 [ 70  80  96]
 [ 62  72  88]
 [ 60  68  85]
 [ 54  59  73]
 [ 53  59  71]
 [ 55  66  76]
 [ 60  71  79]
 [ 69  73  87]
 [ 65  68  87]
 [ 64  73  87]
 [ 64  75  87]
 [ 67  75  88]
 [ 63  73  85]
 [ 67  74  91]
 [ 68  78  94]
 [ 69  80  91]
 [ 71  82  92]
 [ 75  80  97]
 [ 75  81  94]
 [ 67  77  89]
 [ 65  74  84]
 [ 64  70  81]
 [ 73  78  90]
 [ 64  74  86]
 [ 69  79  92]
 [ 70  80  95]
 [ 80  86  98]
 [ 76  83  95]
 [ 69  79  90]
 [ 70  76  88]
 [ 64  74  84]
 [ 65  76  87]
 [ 68  75  87]
 [ 76  82  94]
 [ 74  82  97]
 [ 73  83  94]
 [ 76  86  98]
 [ 81  

C:\Users\addinedu\AppData\Local\Temp\ipykernel_9532\3542972685.py:6: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


[[201 215 216]
 [205 218 220]
 [203 217 218]
 [202 216 217]
 [201 215 216]
 [201 215 216]
 [203 217 218]
 [204 216 223]
 [204 215 222]
 [202 216 222]
 [209 219 226]
 [209 220 223]
 [209 220 221]
 [207 219 221]
 [208 221 227]
 [208 222 223]
 [211 222 224]
 [155 168 175]
 [ 97 109 117]
 [ 87 100 108]
 [ 82  95 104]
 [ 82  93 102]
 [ 83  93 109]
 [ 71  81  97]
 [ 61  72  85]
 [ 65  71  85]
 [ 70  77  92]
 [ 75  80  94]
 [ 66  72  87]
 [ 62  68  81]
 [ 54  60  72]
 [ 53  57  70]
 [ 54  60  72]
 [ 66  71  84]
 [ 64  70  83]
 [ 62  71  83]
 [ 57  67  83]
 [ 64  75  85]
 [ 69  75  89]
 [ 65  74  88]
 [ 68  78  89]
 [ 66  76  87]
 [ 67  77  93]
 [ 70  81  90]
 [ 72  83  92]
 [ 73  84  93]
 [ 71  82  93]
 [ 64  75  86]
 [ 66  71  84]
 [ 72  77  90]
 [ 68  74  86]
 [ 72  77  89]
 [ 69  79  95]
 [ 72  83  95]
 [ 73  83  94]
 [ 74  81  93]
 [ 72  77  88]
 [ 63  69  79]
 [ 72  78  89]
 [ 76  82  92]
 [ 73  83  92]
 [ 71  83  94]
 [ 74  84  95]
 [ 72  85  96]
 [ 78  91 101]
 [ 80  91 101]
 [ 83  90 

KeyboardInterrupt: 

: 

In [7]:
import cv2
import time
import numpy as np

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def draw_rect(frame, regressor, classificator, stride, anchor_count, column, row, anchor, offset):
    index = (int(row * 128 / stride) + column) * anchor_count + anchor + offset

    score = sigmoid(regressor[index][0])
    if score < 0.5: return
    print("regressor[index]")
    print(regressor[index])

    print("index")
    print(index)
    print(classificator[index])
    print(classificator[index].shape)
    print()
    x, y, w, h = classificator[index][:4]

    x += (column + 0.5) * stride - w / 2
    y += (row    + 0.5) * stride - h / 2
    x = int(x)
    y = int(y)
    w = int(w)
    h = int(h)
    frame = cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 1)

net = cv2.dnn.readNet('palm_detection.onnx')
outNames = net.getUnconnectedOutLayersNames()
print(outNames)
frame = cv2.imread("frame.jpg")

frame = cv2.resize(frame, dsize=(128, 128))
frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

#print(frame[100])
#tensor = (frame / 127.5 - 1.0).reshape((128, 128, 3)).transpose(2, 0, 1)
tensor = (frame / 127.5 - 1.0)
#print(tensor[100])
blob = cv2.dnn.blobFromImage(tensor.astype(np.float32), swapRB=False, crop=False)

net.setInput(blob)
preds = net.forward(outNames)
regressor = preds[0]
classifier = preds[1]
print(regressor.shape)
print(classifier.shape)
for y in range(16):
    for x in range(16):
        for a in range(2):
            draw_rect(frame, regressor[0], classifier[0], 8, 2, x, y, a, 0)

for y in range(8):
    for x in range(8):
        for a in range(6):
            draw_rect(frame, regressor[0], classifier[0], 16, 6, x, y, a, 512)

frame = cv2.resize(frame, dsize=(640, 480))

frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
cv2.imshow('Camera Streaming', frame)
cv2.waitKey(0)
cv2.destroyAllWindows()


('classificators', 'regressors')
(1, 896, 1)
(1, 896, 18)
regressor[index]
[0.04977128]
index
280
[ 2.611551    4.446102   23.228807   23.22881     7.7935433  16.332094
  4.107978   -8.3475275   4.5694666  -5.011982    3.3572583   0.21145213
  1.2179537   6.3606343   2.9681916  10.522024   -4.0859804   1.7255598 ]
(18,)

regressor[index]
[0.5224755]
index
281
[ 2.361145    4.699095   24.591116   24.591118    8.161845   16.830046
  4.1837444  -8.197652    4.7591777  -4.90211     3.5825298   0.40529943
  1.207943    6.8262177   3.242042   10.915972   -4.3328857   1.9542971 ]
(18,)

regressor[index]
[0.08604574]
index
282
[-3.309195   4.186873  20.177408  20.177406   0.9614515 14.6024
 -3.8852627 -6.9093394 -3.8447492 -3.8061461 -4.532882   0.8807792
 -5.533393   6.2960033 -2.2406585  9.323646  -7.2694817  1.4503683]
(18,)

regressor[index]
[0.5060289]
index
283
[-3.9204876   4.6823435  21.351051   21.35105     0.67989457 15.112009
 -4.259111   -6.707849   -4.2134857  -3.566737   -4.83386

C:\Users\addinedu\AppData\Local\Temp\ipykernel_9116\2008613688.py:6: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))
